import { PrismaClient } from '@prisma/client-users'
import * as bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.warn('🌱 Starting users seed...')

  // Clear existing data
  await prisma.user.deleteMany()

  // Create 20 users (IDs auto-generated by Prisma)
  const users = []
  for (let i = 1; i <= 20; i++) {
    const hashedPassword = await bcrypt.hash(`password${i}`, 10)
    const user = await prisma.user.create({
      data: {
        email: `user${i}@example.com`,
        name: `User ${i}`,
        password: hashedPassword,
      },
    })
    users.push(user)
    console.warn(`Created user: ${user.email}`)
  }

  console.warn(`✅ Created ${users.length} users`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
